# Generated by Django 5.1 on 2026-03-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='barbers/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('color_tag', models.CharField(default='#D4AF37', help_text='Color hexadecimal para el calendario', max_length=7)),
                ('total_cuts', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='users.barbershop')),
                ('specialties', models.ManyToManyField(blank=True, related_name='specialist_barbers', to='services.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
            },
        ),
    ]
