# Generated by Django 5.1 on 2026-04-20 23:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_reel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(help_text='Video MP4 vertical (9:16 recomendado)', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='reels/'),
        ),
    ]
