# Generated by Django 5.1 on 2026-04-23 18:31

from django.db import migrations


def make_frank_barber(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    Barbershop = apps.get_model('users', 'Barbershop')
    Barber = apps.get_model('barbers', 'Barber')

    # Encontrar al líder de piso (Frank) por su rol
    profiles = UserProfile.objects.filter(role='operational_admin')
    
    if not profiles.exists():
        users = User.objects.filter(username__icontains='frank')
        if not users.exists():
            return
        user = users.first()
        barbershop = Barbershop.objects.first()
    else:
        profile = profiles.first()
        user = profile.user
        barbershop = profile.barbershop or Barbershop.objects.first()

    if not barbershop:
        barbershop = Barbershop.objects.create(name='Área 30 Barber Club')

    Barber.objects.get_or_create(
        user=user,
        defaults={
            'barbershop': barbershop,
            'display_name': user.first_name or 'Frank',
            'is_available': True,
            'color_tag': '#D4AF37'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_update_barber_schedules'),
    ]

    operations = [
        migrations.RunPython(make_frank_barber),
    ]
