# Generated by Django 5.1 on 2026-04-23 18:36

from django.db import migrations


def fix_empty_schedules(apps, schema_editor):
    Barber = apps.get_model('barbers', 'Barber')
    new_schedule = {
        'monday': {'start': '10:00', 'end': '20:00'},
        'tuesday': {'start': '10:00', 'end': '20:00'},
        'wednesday': {'start': '10:00', 'end': '20:00'},
        'thursday': {'start': '10:00', 'end': '20:00'},
        'friday': {'start': '10:00', 'end': '20:00'},
        'saturday': {'start': '09:00', 'end': '21:00'},
        'sunday': {'start': '10:00', 'end': '15:00'},
    }
    for barber in Barber.objects.all():
        if not barber.schedule or barber.schedule == {}:
            barber.schedule = new_schedule
            barber.save()

class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_frank_as_barber'),
    ]

    operations = [
        migrations.RunPython(fix_empty_schedules),
    ]
