# Generated by Django 5.1 on 2026-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_frank_fix_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden de aparición en la web pública'),
        ),
    ]
