# Generated by Django 5.1 on 2026-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0009_barber_unavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje de comisión estándar (0-100)', max_digits=5),
        ),
    ]
