# Generated by Django 6.0.4 on 2026-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0012_sunday_last_slot_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='ledger_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
