# Generated by Django 5.0.6 on 2026-10-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0014_barber_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='only_custom_hours',
            field=models.BooleanField(default=False, help_text='Solo recibe reservas en los horarios de trabajo que él elija'),
        ),
    ]
