# Generated by Django 5.1 on 2026-04-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_galleryimage'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('individual', 'Servicio Individual'), ('silver', 'Membresía Silver'), ('gold', 'Membresía Gold'), ('diamond', 'Membresía Diamond'), ('vip', 'VIP / Exclusivo Frank')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='exclusive_barber',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para servicio disponible para todos los barberos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_services', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='service',
            name='includes_beverage',
            field=models.BooleanField(default=False, help_text='Si activa, descuenta automáticamente bebida del inventario al confirmar venta.'),
        ),
    ]
