# Generated by Django 6.0.4 on 2026-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_fix_dama_exclusive_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_consultation',
            field=models.BooleanField(default=False, help_text='Si está activo, el botón "reservar" abre WhatsApp en lugar de iniciar el flujo de reserva.'),
        ),
    ]
