# Generated by Django 5.1 on 2026-04-19 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0002_galleryimage'),
        ('bookings', '0002_blockeddate'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_reference', models.BooleanField(default=False, help_text='Si requiere número de comprobante (ej: Transferencia)')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, help_text='Ingresos brutos por ventas (sin propinas)', max_digits=12)),
                ('total_tips', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_commissions', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('net_income', models.DecimalField(decimal_places=0, default=0, help_text='(Ventas - Comisiones - Egresos Variables)', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='SuperAdmin verifica que el cuadre sea correcto y consignado')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_daily_closes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre Diario',
                'verbose_name_plural': 'Cierres Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('expense_type', models.CharField(choices=[('fixed', 'Fijo (Arriendo, Servicios, Nómina)'), ('variable', 'Variable (Mantenimiento, Compras menores)'), ('inventory', 'Compra de Inventario')], default='variable', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('included_in_daily_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cashflow.dailyclose')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount_assumed_by', models.CharField(choices=[('company', 'Empresa'), ('barber', 'Barbero'), ('none', 'No aplica')], default='none', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='barbers.barber')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='bookings.booking')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL)),
                ('included_in_daily_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cashflow.dailyclose')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.paymentmethod')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'verbose_name': 'Venta / Checkout',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('basis_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=0, default=0, help_text='100% de propinas va para el barbero', max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='barbers.barber')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='cashflow.sale')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
