# Generated by Django 5.1 on 2026-04-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='¿Ya fue pagada esta comisión al barbero?'),
        ),
        migrations.AddField(
            model_name='commission',
            name='is_paid_in_daily_close',
            field=models.BooleanField(default=False, help_text='Usado para liquidaciones diarias automatizadas (ej. Frank)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
