# Generated by Django 5.1 on 2026-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_commission_is_paid_commission_is_paid_in_daily_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
