# Generated by Django 5.1 on 2026-05-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_sale_approval_status_sale_approved_at_and_more'),
        ('inventory', '0002_inventoryitem_image_inventoryitem_sale_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='total_inventory_sales',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Ingresos por ventas directas de inventario (bebidas, etc.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='net_income',
            field=models.DecimalField(decimal_places=0, default=0, help_text='(Ventas Servicios + Ventas Inventario - Comisiones - Egresos Variables)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Ingresos brutos por ventas de servicios (sin propinas)', max_digits=12),
        ),
        migrations.CreateModel(
            name='InventorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('included_in_daily_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sales', to='cashflow.dailyclose')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_sales', to='inventory.inventoryitem')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.paymentmethod')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de Inventario',
                'verbose_name_plural': 'Ventas de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
