# Generated by Django 5.1 on 2026-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_dailyclose_total_inventory_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='added_value_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='added_value_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
