# Generated by Django 6.0.4 on 2026-06-16 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0010_barber_commission_percentage'),
        ('cashflow', '0006_sale_added_value_amount_sale_added_value_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Motivo del préstamo / vale', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_settled', models.BooleanField(default=False, help_text='¿Ya fue descontado en una liquidación al barbero?')),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='barbers.barber')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_advances_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adelanto / Vale de Barbero',
                'verbose_name_plural': 'Adelantos / Vales de Barberos',
                'ordering': ['-created_at'],
            },
        ),
    ]
