# Generated by Django 5.0.6 on 2026-07-10 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0010_barber_commission_percentage'),
        ('cashflow', '0008_alter_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberadvance',
            name='settled_in_daily_close',
            field=models.ForeignKey(blank=True, help_text='Cierre diario en el que se liquidó este vale (solo Frank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_advances', to='cashflow.dailyclose'),
        ),
        migrations.CreateModel(
            name='BarberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('suggested_amount', models.DecimalField(decimal_places=0, default=0, help_text='Saldo sugerido por el sistema al momento del pago', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='barbers.barber')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_payments_made', to=settings.AUTH_USER_MODEL)),
                ('daily_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_payments', to='cashflow.dailyclose')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_payments', to='cashflow.expense')),
            ],
            options={
                'verbose_name': 'Pago a Barbero',
                'verbose_name_plural': 'Pagos a Barberos',
                'ordering': ['-created_at'],
            },
        ),
    ]
