# Generated by Django 5.0.6 on 2026-07-10 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_barberadvance_settled_in_daily_close_barberpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Caja Enviada',
                'verbose_name_plural': 'Alertas de Caja Enviadas',
            },
        ),
        migrations.AddConstraint(
            model_name='cashflowalertlog',
            constraint=models.UniqueConstraint(fields=('alert_type', 'date'), name='uniq_cashflow_alert_per_day'),
        ),
    ]
