# Generated by Django 5.0.6 on 2026-07-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_cashflowalertlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberadvance',
            name='settled_in_payment',
            field=models.ForeignKey(blank=True, help_text='Pago en el que se descontó este vale (barberos no-Frank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_advances', to='cashflow.barberpayment'),
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_in_payment',
            field=models.ForeignKey(blank=True, help_text='Pago en el que se liquidó esta comisión (barberos no-Frank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='cashflow.barberpayment'),
        ),
    ]
