# Generated by Django 6.0.4 on 2026-07-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_barberadvance_settled_in_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberpayment',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], default='cash', help_text='De dónde salió el dinero: efectivo o transferencia', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], default='cash', help_text='De dónde salió el dinero: efectivo o transferencia', max_length=10),
        ),
    ]
