# Generated by Django 5.0.6 on 2026-07-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_barberpayment_payment_source_expense_payment_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('cash_balance', models.DecimalField(decimal_places=0, default=0, help_text='Saldo de efectivo en el momento del corte', max_digits=12)),
                ('transfer_balance', models.DecimalField(decimal_places=0, default=0, help_text='Saldo de transferencia en el momento del corte', max_digits=12)),
                ('withdrew_cash', models.BooleanField(default=False, help_text='¿Se retiró el efectivo al cerrar? Si sí, el período siguiente arranca en $0')),
                ('withdrew_transfer', models.BooleanField(default=False, help_text='¿Se retiró el saldo de la cuenta al cerrar?')),
                ('opening_cash', models.DecimalField(decimal_places=0, default=0, help_text='Con cuánto efectivo arranca el período siguiente', max_digits=12)),
                ('opening_transfer', models.DecimalField(decimal_places=0, default=0, help_text='Con cuánto saldo de cuenta arranca el período siguiente', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_cuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Inyección de dinero'), ('withdrawal', 'Retiro de dinero'), ('transfer', 'Traslado entre cajas'), ('adjustment', 'Ajuste de saldo')], max_length=12)),
                ('source', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], help_text='Caja afectada. En un traslado, la caja de ORIGEN.', max_length=10)),
                ('to_source', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], help_text='Solo en traslados: la caja de DESTINO.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_cut', models.ForeignKey(blank=True, help_text='Corte que archivó este movimiento. Vacío = período en curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='cashflow.cashcut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
