# Generated by Django 5.0.6 on 2026-07-26 20:25

from django.db import migrations, models

# Firma del corte que crea set_cash_starting_point(): retira ambas cajas, abre
# el período siguiente en cero y deja esa nota. Los cortes de punto de partida
# creados ANTES de que existiera el campo quedarían en False y por lo tanto
# revertibles — que es justo la operación que hay que impedir.
STARTING_POINT_NOTE = 'Punto de partida'


def marcar_puntos_de_partida(apps, schema_editor):
    CashCut = apps.get_model('cashflow', 'CashCut')
    CashCut.objects.filter(
        withdrew_cash=True, withdrew_transfer=True,
        opening_cash=0, opening_transfer=0,
        notes__startswith=STARTING_POINT_NOTE,
    ).update(is_starting_point=True)


def desmarcar(apps, schema_editor):
    CashCut = apps.get_model('cashflow', 'CashCut')
    CashCut.objects.update(is_starting_point=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_cashcut_cashmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcut',
            name='is_starting_point',
            field=models.BooleanField(default=False, help_text='Corte generado al fijar el punto de partida. No se puede deshacer: hacerlo devolvería el saldo al histórico roto que ese corte vino a cerrar.'),
        ),
        migrations.RunPython(marcar_puntos_de_partida, desmarcar),
    ]
