# Generated by Django 5.0.6 on 2026-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_cashcut_is_starting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberadvance',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], default='', help_text='De dónde salió el dinero: efectivo o transferencia (vacío = vale histórico, no descuenta de la caja)', max_length=10),
        ),
    ]
