# Generated by Django 5.0.6 on 2026-09-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_barberadvance_payment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('none', 'No salio de caja')], default='cash', help_text='De dónde salió el dinero: efectivo, transferencia, o ninguna ("no salió de caja": insumo que puso el barbero o que ya estaba pagado). Solo efectivo y transferencia descuentan del control de caja.', max_length=10),
        ),
    ]
