# Generated by Django 5.1 on 2026-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('operational_admin', 'Administrador Operativo'), ('admin', 'Admin de Barbería'), ('barber', 'Barbero')], default='barber', max_length=25),
        ),
    ]
