# Generated by Django 5.1 on 2026-04-19 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_blockeddate'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('beverage', 'Bebida'), ('hair_product', 'Producto Capilar'), ('consumable', 'Consumible'), ('other', 'Otro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='unidad', help_text='Ej: unidad, botella, litro, gramo', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=5, help_text='Nivel mínimo; se genera alerta si quantity <= minimum_stock', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida por Servicio'), ('adjustment', 'Ajuste Manual'), ('purchase', 'Compra'), ('waste', 'Desperdicio / Merma')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='bookings.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_service', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='inventory.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='services.service')),
            ],
            options={
                'verbose_name': 'Consumo de Inventario por Servicio',
                'verbose_name_plural': 'Consumos de Inventario por Servicio',
                'unique_together': {('service', 'item')},
            },
        ),
    ]
