# Generated by Django 5.1 on 2026-04-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del producto (mostrada en el selector del checkout)', null=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio de venta al consumidor (ej. cerveza $5,000)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo interno de compra por unidad', max_digits=10),
        ),
    ]
