# Generated by Django 5.1 on 2026-04-29 03:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyROISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mes (1-12)')),
                ('gross_income', models.DecimalField(decimal_places=0, default=0, help_text='Suma total de final_price de todas las Sales del mes.', max_digits=15, verbose_name='Ingresos Brutos (Ventas)')),
                ('total_commissions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Comisiones Barberos')),
                ('total_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Egresos')),
                ('net_income', models.DecimalField(decimal_places=0, default=0, help_text='gross_income - total_commissions - total_expenses', max_digits=15, verbose_name='Ganancia Neta del Mes')),
                ('is_locked', models.BooleanField(default=False, help_text='Una vez bloqueado no puede modificarse.', verbose_name='¿Cerrado/Bloqueado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Snapshot Mensual ROI',
                'verbose_name_plural': 'Snapshots Mensuales ROI',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre del Socio')),
                ('share_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje de las ganancias netas que le corresponde a este socio.', max_digits=5, verbose_name='% de participación')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Monto Invertido (COP)')),
                ('description', models.CharField(blank=True, help_text='Ej: Aporte inicial, Compra de equipos, Adecuaciones locativas…', max_length=255, verbose_name='Descripción')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Aporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='roi.partner', verbose_name='Socio')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Inversión del Socio',
                'verbose_name_plural': 'Inversiones de Socios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerMonthlyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Aplicado')),
                ('gross_share', models.DecimalField(decimal_places=0, default=0, help_text='net_income * share_percentage / 100', max_digits=15, verbose_name='Monto Bruto a Recibir')),
                ('investment_balance_before', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Saldo de Inversión Pendiente (Inicio del Mes)')),
                ('amortization_applied', models.DecimalField(decimal_places=0, default=0, help_text='min(gross_share, investment_balance_before)', max_digits=15, verbose_name='Amortización Aplicada')),
                ('investment_balance_after', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Saldo de Inversión Pendiente (Fin del Mes)')),
                ('cash_out', models.DecimalField(decimal_places=0, default=0, help_text='gross_share - amortization_applied', max_digits=15, verbose_name='Disponible para el Socio (Efectivo)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_shares', to='roi.partner')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_shares', to='roi.monthlyroisnapshot')),
            ],
            options={
                'verbose_name': 'Participación Mensual de Socio',
                'verbose_name_plural': 'Participaciones Mensuales de Socios',
                'unique_together': {('snapshot', 'partner')},
            },
        ),
    ]
