# Generated by Django 5.0.6 on 2026-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0002_snapshot_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyroisnapshot',
            name='total_operational_expenses',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Expense.amount de todo lo que no es un gasto fijo, excluyendo el "Pago Diario: Franko" automático (ya está en comisiones). Un bono suelto a un barbero sí cuenta: es gasto real.', max_digits=15, verbose_name='Egresos Operativos (Día a día + Inventario + Materiales)'),
        ),
    ]
