# Generated by Django 5.1 on 2026-04-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Ej: 10% de descuento en servicios (usar 10.00)', max_digits=5)),
                ('monthly_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('free_drinks_per_month', models.IntegerField(default=0, help_text='Cantidad de bebidas gratis al mes (ej: 2 cervezas)')),
            ],
            options={
                'verbose_name': 'Nivel de Membresía',
                'verbose_name_plural': 'Niveles de Membresía',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('membership_active_until', models.DateField(blank=True, null=True)),
                ('habeas_data_accepted', models.BooleanField(default=False, help_text='True si aceptó política de tratamiento de datos al agendar/registrarse')),
                ('habeas_data_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.membershiptier')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
