# Generated by Django 5.1 on 2026-04-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_galleryimage'),
        ('bookings', '0002_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='Cliente presencial sin reserva previa (ej. Cliente General)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='privacy_accepted',
            field=models.BooleanField(default=False, help_text='Aceptación obligatoria de políticas de privacidad y tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(blank=True, help_text='Puede quedar vacío inicialmente si eligen "Cualquier barbero"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='barbers.barber'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_rating', models.PositiveSmallIntegerField(default=5)),
                ('shop_rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Determina si se muestra en el frontend (ej. solo >= 4 estrellas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Reseña / Calificación',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
