# Generated by Django 5.1 on 2026-04-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_walk_in_booking_privacy_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='survey_sent',
            field=models.BooleanField(default=False),
        ),
    ]
