# Generated by Django 5.1 on 2026-04-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_survey_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Opcional', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Opcional', max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Buzón de Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
