# Generated by Django 5.1 on 2026-04-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddate',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Opcional. Si se define (junto con end_time), el día no estará completamente bloqueado, sino que se limitará a trabajar solo en este horario (ej: 10:00 a 14:00).', null=True),
        ),
    ]
