# Generated by Django 5.1 on 2026-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0009_barber_unavailability'),
        ('bookings', '0007_blockeddate_end_time_blockeddate_start_time'),
        ('services', '0003_add_dama_services'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('barber', 'date', 'time'), name='unique_active_booking_barber_date_time'),
        ),
    ]
