# Generated by Django 6.0.4 on 2026-05-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_unique_active_booking_barber_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_materials_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
