# Generated by Django 5.0.6 on 2026-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_manual_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='close_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
