# Generated by Django 5.1 on 2026-04-21 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('price_change', 'Cambio de precio'), ('promotion', 'Promoción / Descuento'), ('daily_close', 'Cierre de caja'), ('payment', 'Registro de pago'), ('refund', 'Reembolso'), ('inventory', 'Movimiento de inventario'), ('commission', 'Comisión registrada')], max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
